server:
  port: 8083

spring:
  application:
    name: mission-service
  datasource:
    url: jdbc:postgresql://postgres-mission:5433/mission_db
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    hostname: mission-service
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: false

app:
  jwt:
    secret: YTFiMmMzZDRlNWY2ZzdoOGk5ajBrMWwybTNuNG81cDY3cThyOXMwdTF2MnczeDR5NXo2YTdiOGM5ZA==
    expirationMinutes: 30
