services:

  # ===== KAFKA (KRaft) =====
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    restart: always
    ports:
      - "29092:29092"
    environment:
      CLUSTER_ID: r4zt_wrqT6e0YJ2k2eQ6cA
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - kafka_data:/var/lib/kafka/data
  # ===== POSTGRESQL AVEC PGVECTOR =====
  postgres-identity:
    image: pgvector/pgvector:pg16
    container_name: postgres-identity
    restart: always
    environment:
      POSTGRES_DB: identity_db
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_pass
    ports:
      - "5436:5432"
    volumes:
      - pg_identity_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U identity_user -d identity_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - plateforme-engagement-network

  # ===== DISCOVERY SERVICE (EUREKA SERVER) =====
  discovery-service:
    build:
      context: ./infrastructure/discovery-service
      dockerfile: Dockerfile
    container_name: discovery-service
    restart: always
    ports:
      - "8761:8761"
    environment:
      SPRING_APPLICATION_NAME: discovery-service
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8761/actuator/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - plateforme-engagement-network

  # ===== IDENTITY SERVICE (Spring Boot) =====
  identity-service:
    build:
      context: ./epic-1-authentication/backend/iam-service
      dockerfile: Dockerfile
    container_name: identity-service
    restart: always
    ports:
      - "8081:8081"
    volumes:
      - identity_images:/app/assets/images
    environment:
      SPRING_APPLICATION_NAME: identity-service
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-identity:5432/identity_db
      SPRING_DATASOURCE_USERNAME: identity_user
      SPRING_DATASOURCE_PASSWORD: identity_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
      JWT_SECRET: YTFiMmMzZDRlNWY2ZzdoOGk5ajBrMWwybTNuNG81cDY3cThyOXMwdTF2MnczeDR5NXo2YTdiOGM5ZA==
      APP_UPLOAD_PATH: /app/assets/images
    depends_on:
      postgres-identity:
        condition: service_healthy
      discovery-service:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8081/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - plateforme-engagement-network


  # ===== API GATEWAY =====
  api-gateway:
    build:
      context: ./infrastructure/api-gateway
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: api-gateway
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discovery-service:8761/eureka
    depends_on:
      discovery-service:
        condition: service_healthy
      identity-service:
        condition: service_healthy

    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - plateforme-engagement-network

  # ===== FRONTEND =====
  frontend:
    build:
      context: ./shared/frontend
      dockerfile: Dockerfile
      args:
        API_URL: http://localhost:8080
    container_name: frontend
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - api-gateway

volumes:
  pg_identity_data:
  identity_images:
  kafka_data:

networks:
  plateforme-engagement-network:
    external: true