server:
  port: 8084

spring:
  application:
    name: user-profile-service

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      group-id: user-profile-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.pfe.userprofile.*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.pfe.userprofile.event.UserCreatedEvent
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

  datasource:
    url: jdbc:postgresql://postgres-user-profile:5432/user_profile_db
    username: user_profile_user
    password: user_profile_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  web:
    resources:
      static-locations: file:${app.upload.path:/app/assets/images/}
      add-mappings: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: YTFiMmMzZDRlNWY2ZzdoOGk5ajBrMWwybTNuNG81cDY3cThyOXMwdTF2MnczeDR5NXo2YTdiOGM5ZA==
  expiration: 1800000   # 30 minutes en millisecondes

app:
  kafka:
    topics:
      user-created: com.engagement.iam.user.registered
  upload:
    path: ${UPLOAD_PATH:/app/assets/images}
    url-prefix: /uploads/

logging:
  level:
    com.pfe.userprofile.config: DEBUG