server:
  port: 8085

spring:
  application:
    name: team-management-service

  datasource:
    url: jdbc:postgresql://postgres-team-management:5432/team_management_db
    username: team_management_user
    password: team_management_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    instance-id: ${spring.application.name}:${server.port}
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info

jwt:
  secret: YTFiMmMzZDRlNWY2ZzdoOGk5ajBrMWwybTNuNG81cDY3cThyOXMwdTF2MnczeDR5NXo2YTdiOGM5ZA==
  expiration: 1800000

app:
  user-profile:
    service-url: http://user-profile-service:8084

logging:
  level:
    com.pfe.teammanagement: DEBUG